### ISSUE TITLE
Magento 2.1.2 rule doesn't include the configurable

### ISSUE THREAD

**Issue by PascalBrouwers** [karliuka/m2.SmartCategory#1]
Hi @karliuka,

I tried your module and in the backend it works great. Tested it with magento 2.1.2 with sample data and filled a categorie with only Red items:

![screen shot 2017-01-11 at 11 55 30](https://cloud.githubusercontent.com/assets/17834386/21845923/e51db844-d7f4-11e6-9158-8789ff0a0a3c.png)

Then I saved the category, cleared cache and run the indexers, but no products show up:
![screen shot 2017-01-11 at 11 55 55](https://cloud.githubusercontent.com/assets/17834386/21845954/045acb7a-d7f5-11e6-974c-cd2a04b7f661.png)

What happens it that my rule only selects the simple products of the configurable. Is there a way to include the configurable?

**Comment by karliuka** [comment]
Thank you, I know about the problem and looking for a solution already.

**Comment by PascalBrouwers** [comment]
If you have an ideas maybe I can help

**Comment by karliuka** [comment]
Thank you, The first [idea](https://github.com/karliuka/m2.SmartCategoryConfigurable) of replacing children's on parents realized easily. The second idea of forced show of only children on storefront is more complicated. The third idea I do not know.
