### ISSUE TITLE
Magento 2.2 error

### ISSUE THREAD

**Issue by georgios-2317** [karliuka/m2.SmartCategory#10]
With category set as anchor (for layered navigation) and smart_category enabled the following error occurs.

"You cannot define a correlation name 'smart_category' more than once"

Furthermore, the category in Admin states 9 (in my case) products but the front-end states nothing found. Using "Is New" condition.

**Comment by georgios-2317** [comment]
Patch to prevent adding the join twice, if you're interested:

> Faonni\SmartCategory\Observer\ProductListObserver


```
class ProductListObserver implements ObserverInterface
{	
    /**
     * Handler for product match event
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer)
    {		
		$collection = $observer->getEvent()->getCollection();
		$select = $collection->getSelect();
		$connection = $select->getConnection();	


		if (!$collection->hasFlag('smart_category')) {
            error_log("joining with smart_category");
            $select
                ->joinLeft(
                    ['smart_category' => $collection->getTable('faonni_smartcategory_rule')],
                    'cat_index.category_id = smart_category.rule_id',
                    []
                );
            $collection->setFlag('smart_category', true);
        }
        return $this;
    }
}  
```

**Comment by karliuka** [comment]
Thank you. I think this observer is deprecated (maybe I forgot to remove it) ... need some time ..

**Comment by georgios-2317** [comment]
Thats fine. It works on my side now (observer called fine). At least the error goes away. Now testing rest of functionality.

**Comment by karliuka** [comment]
Yes, these were [old experiments](https://github.com/karliuka/m2.SmartCategorySale/commit/ba751b1bf9c1d936f983918189acdd75cc202da2) .
Frontend it does not use.
Please, update the module.

**Comment by georgios-2317** [comment]
Haven't done an update before but here it is: https://github.com/karliuka/m2.SmartCategorySale/commit/7433b90588979a54b1950e96070991066bfda268

**Comment by karliuka** [comment]
it's all in the past. do not install these modules now.

**Comment by georgios-2317** [comment]
It works fine to be honest (with patch). Thank you anyway

**Comment by karliuka** [comment]
and thank you
