### ISSUE TITLE
Error: "Please specify a rule."

### ISSUE THREAD

**Issue by fwegberts** [karliuka/m2.SmartCategory#12]
Hi,

Im am using:
Magento ver. 2.2.2

The error is shown when saving a category were a smart rule is applied. When we open the "Products in Category " tab and then save the category, the error is gone

**Comment by karliuka** [comment]
Hi,
Thank you, 
I'll take a look

**Comment by karliuka** [comment]
This is fixed. Check, please.

**Comment by fwegberts** [comment]
Can you give me the ssh composer update command?

Btw: this is one of the best extensions i know, thx :) Saves ALOT of time.




Met vriendelijke groet,
Frank Egberts
Kingdo
Voetbalshirtskoning.nl

2018-02-21 20:43 GMT+01:00 Karliuka Vitalii <notifications@github.com>:

**Comment by karliuka** [comment]
update only smart category package 
`composer update faonni/module-smart-category`

update all magento2 packages
`composer update`

**Comment by fwegberts** [comment]
Works. Thanks!
