### ISSUE TITLE
Update on save indexer issue

### ISSUE THREAD

**Issue by fwegberts** [karliuka/m2.SmartCategory#15]
Hi,

In Magento 2.1.4 saving a product is not working when we set Smart Category Product Rule indexer to "update on save". When we set the indexer to "update by schedule" we can save products again. But the Smart Category Product Rule indexer is not updating. How many times does the indexer update per day?

**Comment by karliuka** [comment]
Hi,

The start time of the indexer is determined by the settings of the cron of the group 'index'.
'update on save' mode  I will take a look.

**Comment by karliuka** [comment]
In Update on save mode indexer run as soon as a change and  save  category or product in the admin panel. 
For rules that have a time dependence, this mode is not suitable, because it does not run on the cron.
Update By Schedule mode have dependent on the cron. Have you checked the cron settings?
