### ISSUE TITLE
Smart Category Configurable

### ISSUE THREAD

**Issue by inelukipg** [karliuka/m2.SmartCategory#2]
Hi @karliuka,
Do I need to install Smart Category Configurable separately or is it included in SmartCategory?

**Comment by karliuka** [comment]
SmartCategoryConfigurable expands the functionality of SmartCategory and not used individually.

**Comment by inelukipg** [comment]
Ok, thanks! 
If I understand this correct, this includes them both? 
https://packagist.org/packages/faonni/module-smart-category-kit

**Comment by karliuka** [comment]
Yes, this is my plan for the future)
composer require faonni/module-smart-category-kit
or
composer require faonni/module-smart-category
module-smart-category-configurable is installed automatically anyway as dependence

**Comment by inelukipg** [comment]
Ok, 
Thank you for the answer!
