### ISSUE TITLE
Compatibility Magento 2.3

### ISSUE THREAD

**Issue by fwegberts** [karliuka/m2.SmartCategory#28]
Hi,

Great extension, good work. Is this already compatible with Magento 2.3?

**Comment by karliuka** [comment]
Hi,

Thank you, not yet, in progress ...

**Comment by fwegberts** [comment]
Ok, do you have a indication when it is ready?

**Comment by nihillo** [comment]
Hi,
Same question here, we find your extension will be very useful for a Magento 2.3 site we are developing, have you got an estimation when it will be compatible?

Thanks,

**Comment by fwegberts** [comment]
Hi,

Any news on this?

**Comment by MichielTG** [comment]
Plug-in still seems to work properly for me on Magento 2.3 - https://github.com/karliuka/m2.SmartCategory/pull/33

**Comment by nihillo** [comment]
@MichielTG thanks, I manually installed it and seems to be correctly working as well.

**Comment by MichielTG** [comment]
@karliuka Updated the files, so this topic may be closed.

**Comment by karliuka** [comment]
Yes, today the plugin is installed through the composer, but there will be more changes.

**Comment by MichielTG** [comment]
Great, good job.
