### ISSUE TITLE
PHP 7.1.16 not supported

### ISSUE THREAD

**Issue by fwegberts** [karliuka/m2.SmartCategory#29]
Hi,

when installing on magento 2.3 and PHP 7.1.16

magento/module-rule 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.
    - magento/module-rule 100.1.1 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.16) does not satisfy that requirement.

**Comment by Daniel304** [comment]
If j am correct m2.3 has it own smart categories

Op vr 21 dec. 2018 om 15:42 schreef fwegberts <notifications@github.com>

**Comment by fwegberts** [comment]
Nope, only the paid commerce version, not community
