### ISSUE TITLE
Special Price Condition

### ISSUE THREAD

**Issue by inelukipg** [karliuka/m2.SmartCategory#3]
Hi,

I can't find any way to create a smart category for products on special price?
If I use condition: Special Price greater than 0 it also shows products where special price has expired.

**Comment by karliuka** [comment]
Hi, Sorry for the belated reply.
Yes, SmartCategory now does not work directly with the attributes of a special price and a new product.
This idea is now being developed and will soon be merged with the main repository.
[ProductSale](https://github.com/karliuka/m2.ProductSale)
[SmartCategorySale](https://github.com/karliuka/m2.SmartCategorySale)

**Comment by karliuka** [comment]
install SmartCategorySale (including SmartCategorySale and ProductSaleIndexer)
composer require faonni/module-smart-category-sale

or install all SmartCategory kit (SmartCategory, SmartCategoryConfigurable, SmartCategorySale and ProductSaleIndexer)
composer require faonni/module-smart-category-kit
