### ISSUE TITLE
2.0.9

### ISSUE THREAD

**Issue by inelukipg** [karliuka/m2.SmartCategory#4]
Hi,
What's new in version 2.0.9?

**Comment by karliuka** [comment]
Added join needed for modules SmartCategorySale(special price filter) and SmartCategoryNew(in the process).

**Comment by inelukipg** [comment]
Hi,
OK great! I first installed previous version via  _composer require faonni/module-smart-category_

Could i run _composer require faonni/module-smart-category-kit_ now to get the latest of all components?

I'm not so familiar how composer works.

**Comment by karliuka** [comment]
Yes, 'composer require faonni/module-smart-category-kit' will install all the latest components

**Comment by ruihua1970** [comment]
Hi,
Can this extension be used on Magento 2.1.7?
I install it on Magento ver. 2.1.7, I enabled the Smart Category,but I get error when click the save button on Categories page.

1 exception(s):
Exception #0 (ReflectionException): Class Faonni\SmartCategorySale\Observer\ValidateDataObserver does not exist

Exception #0 (ReflectionException): Class Faonni\SmartCategorySale\Observer\ValidateDataObserver does not exist
#0 /var/www/html/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Faonni\\SmartCat...')
#1 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Faonni\\SmartCat...')
#2 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Faonni\\SmartCat...')
#3 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Faonni\\SmartCat...')
.....................

Thank you!


Thank you!
