### ISSUE TITLE
Exception #0 (ReflectionException): Class Faonni\SmartCategorySale\Observer\ValidateDataObserver does not exist

### ISSUE THREAD

**Issue by ruihua1970** [karliuka/m2.SmartCategory#5]
Hi,
Can this extension be used on Magento 2.1.7?
I install it on Magento ver. 2.1.7, I enabled the Smart Category,but I get error when click the save button on Categories page.

1 exception(s):
Exception #0 (ReflectionException): Class Faonni\SmartCategorySale\Observer\ValidateDataObserver does not exist

Exception #0 (ReflectionException): Class Faonni\SmartCategorySale\Observer\ValidateDataObserver does not exist
#0 /var/www/html/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Faonni\SmartCat...')
#1 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Faonni\SmartCat...')
#2 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Faonni\SmartCat...')
#3 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Faonni\SmartCat...')
.....................

Thank you!

**Comment by karliuka** [comment]
Hi,
In most cases you need to delete the directories _var/generation, var/cache, var/view_preprocessed, var/page_cache_ and repeat the command php bin/magento setup:upgrade (optional php bin/magento setup:static-content:deploy).

**Comment by ruihua1970** [comment]
Hi,
Thank you so much for you prompt reply,I reinstall the Magento2 and the Smart Category extension,then I do the step as you said,but still can not save the category when I enabled the smart category on categories page,the error is as below,my magento2 version is 2.1.7.please help me,Thanks again!

Fatal error: Uncaught Error: Class 'Faonni\SmartCategorySale\Observer\ValidateDataObserver' not found in /var/www/html/magento3/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93 Stack trace: #0 /var/www/html/magento3/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Faonni\\SmartCat...', Array) #1 /var/www/html/magento3/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Faonni\\SmartCat...') #2 /var/www/html/magento3/vendor/magento/framework/Event/ObserverFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->get('Faonni\\SmartCat...') #3 /var/www/html/magento3/vendor/magento/framework/Event/Invoker/InvokerDefault.php(59): Magento\Framework\Event\ObserverFactory->get('Faonni\\SmartCat...') #4 /var/www/html/magento3/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\F in /var/www/html/magento3/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

**Comment by karliuka** [comment]
Hi,
Please wait a few days. I'm currently preparing a new release and I think it will be more interesting (sales and new products filters will be in the native rules and the module, with which you have problems, will deleted)

**Comment by ruihua1970** [comment]
Hi,
OK,that is great!!!,I will wait for your new realease,Thank you so much!!

**Comment by karliuka** [comment]
Check, please

**Comment by inelukipg** [comment]
Hi,
Should I  install module-smart-category-sale to use sale products?
I don't really get this "sales and new products filters will be in the native rules and the modul"..?

**Comment by karliuka** [comment]
module-smart-category-sale no need to install. Conditions of SmartCategory have the native rules (Special Price and New) and dynamic processing of dates(from, to).

composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

Go to product list tab of category setting and set your conditions (color, category, attribute set, special price ,New and etc).

**Comment by ruihua1970** [comment]
Hi,
I have checked the new release on Magento 2.1.17,it works like a charm,Thank you so much!!!
