### ISSUE TITLE
Bug in rule with multipleselect atttribute

### ISSUE THREAD

**Issue by Melleschepers** [karliuka/m2.SmartCategory#54]
First of all I want to thanks you for this amazing extension 👍 ! We had an M1 store before and used the same extension from proxiblue.. so I was glad to find out that this extension works for M2.  

Nevertheless, I found a bug that caused invalid products in some categories. I tried to fix it myself but I couldn't figure it out. So that is why I have explained it here as well as possible.

The situation:
![image](https://user-images.githubusercontent.com/13859086/96101576-e6ec4980-0ed5-11eb-92c0-9373bd3da6d0.png)
A rule is applied with a value of 1 multiple select attribute.
eav_attribute_option: 
attribute_id -> 188 (subtheme)
option_id -> 661 (flintstones)

SQL data:
{"type":"Faonni\\SmartCategory\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1","is_value_processed":null,"aggregator":"any","conditions":[{"type":"Faonni\\SmartCategory\\Model\\Rule\\Condition\\Product","attribute":"subtheme","operator":"{}","value":["661"],"is_value_processed":false}]}

Expected output:
Products which contains subtheme = "flintstones" are added to this categorie.

Real output / the problem:
Products which contains the "beetlejuice" value (option_id=6661) are also added to the categorie.

Reason:
The subtheme (attribute_id=188) also has an option_id=6661 (beetlejuice)... so when making the (I think LIKE %661%) sql query...  these items are also added.

Hacky solution: I can add a rule like
![image](https://user-images.githubusercontent.com/13859086/96101528-d8059700-0ed5-11eb-8ccf-1da1d5565101.png)
But when new attribute options are added to subtheme.. this problem will keep repeating again and again.

Other (in my case not working) hacky solution:
![image](https://user-images.githubusercontent.com/13859086/96101751-1307ca80-0ed6-11eb-9051-c8629941a7cc.png)
The products does have multiple options (587,661) in subtheme, so it doens't work.
value_id / attribute_id / store_id / entity_id / value
430475 / 188 / 0 / 7876 / 587,661

Hopefully I have clarified when the problem occurs and what the problem is. If you need more information, let me know!

**Comment by karliuka** [comment]
Thank you for your message. I will check as soon as possible ...

**Comment by Melleschepers** [comment]
fyi; if figure out it's a core bug in magento. So nothing to do with the module since it is depending on Magento rule module ;)
