### ISSUE TITLE
Error on setup:di:compile

### ISSUE THREAD

**Issue by inelukipg** [karliuka/m2.SmartCategory#6]
Hi,
When running setup:di:compile i get following errors.
I'm on Magento 2.1.8

`BErrors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        Faonni\SmartCategory\Model\Rule\Condition\Product\News
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\News in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/News.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
        Faonni\SmartCategory\Model\Rule\Condition\Product\Sale
                Incorrect dependency in class Faonni\SmartCategory\Model\Rule\Condition\Product\Sale in /home/smarthem/www/magento2/vendor/faonni/module-smart-category/Model/Rule/Condition/Product/Sale.php
\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
Total Errors Count: 2`

**Comment by karliuka** [comment]
Hi,
It is fixed. Please update module.
